#!/usr/bin/env python3
from __future__ import annotations

import ast
import re
from pathlib import Path

ROUTES_FILE = Path("apps/api-server/app/api/routes.py")
CONFIG_FILE = Path("apps/api-server/app/core/config.py")
OUTPUT_FILE = Path("docs/API_ROUTE_MAP.generated.md")

HTTP_METHODS = {"get", "post", "put", "delete", "patch"}
DEFAULT_API_PREFIX = "/api/v1"


def configured_api_prefix() -> str:
    if not CONFIG_FILE.exists():
        return DEFAULT_API_PREFIX
    source = CONFIG_FILE.read_text(encoding="utf-8")
    match = re.search(r'api_prefix:\s*str\s*=\s*["\']([^"\']+)["\']', source)
    return match.group(1) if match else DEFAULT_API_PREFIX


def literal_string(node: ast.AST, api_prefix: str) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value

    if isinstance(node, ast.JoinedStr):
        parts: list[str] = []
        for value in node.values:
            if isinstance(value, ast.Constant) and isinstance(value.value, str):
                parts.append(value.value)
                continue
            if isinstance(value, ast.FormattedValue):
                expr = value.value
                if (
                    isinstance(expr, ast.Attribute)
                    and expr.attr == "api_prefix"
                    and isinstance(expr.value, ast.Name)
                    and expr.value.id == "settings"
                ):
                    parts.append(api_prefix)
                    continue
            return None
        return "".join(parts)

    return None


def extract_routes() -> list[tuple[str, str, str]]:
    source = ROUTES_FILE.read_text(encoding="utf-8")
    tree = ast.parse(source)
    api_prefix = configured_api_prefix()

    routes: list[tuple[str, str, str]] = []

    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue

        for deco in node.decorator_list:
            if not isinstance(deco, ast.Call):
                continue
            func = deco.func
            if not isinstance(func, ast.Attribute):
                continue
            method = func.attr.lower()
            if method not in HTTP_METHODS:
                continue
            if not deco.args:
                continue
            path = literal_string(deco.args[0], api_prefix)
            if not path:
                continue
            routes.append((method.upper(), path, node.name))

    return sorted(routes, key=lambda x: (x[1], x[0], x[2]))


def main() -> int:
    if not ROUTES_FILE.exists():
        print(f"ERROR: missing {ROUTES_FILE}")
        return 1

    routes = extract_routes()

    lines = [
        "# Portal Website Generated API Route Map",
        "",
        "> Generated by `scripts/extract_api_routes.py`.",
        "",
        "| Method | Path | Handler |",
        "|---|---|---|",
    ]

    for method, path, handler in routes:
        lines.append(f"| {method} | `{path}` | `{handler}` |")

    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Total routes found: {len(routes)}")
    lines.append("")

    OUTPUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"[api-routes] wrote {OUTPUT_FILE} with {len(routes)} routes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
